### ISSUE TITLE
no screenshot

### ISSUE THREAD

**Issue by krux02** [anvaka/ngraph.forcelayout3d#2]
Can you add a screenshot of a layout that was generated by this algorithm? The technique that was used for the visualization is not important, but I would like the result of this algorithm can look like, before I spend a lot of time to feed it with my data.

**Comment by anvaka** [comment]
You can see interactive version here: http://anvaka.github.io/ngraph.forcelayout3d/demo/

These also use the same core: 
* http://anvaka.github.io/pm/#/?_k=m8xpxd 
* https://github.com/anvaka/ngraph.pixel#demo
